### ISSUE TITLE
yarn generateで`ERROR  aspida is not a function`が出る

### ISSUE THREAD

**Issue by nac-39** [NU-wiki-web/nu-wiki-frontend#76]
```
s ~/workspace/jack/nu-wiki/nu-wiki-frontend  fix-api-client-delete
|･ω･｀)> yarn generate
yarn run v1.22.0
$ nuxt generate
Nuxi 3.0.0                                                                                                     22:32:49
Nuxt 3.0.0 with Nitro 1.0.0                                                                                    22:32:49

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.


 WARN  Browserslist: caniuse-lite is outdated. Please run:                                                     22:32:50
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

ℹ Client built in 5747ms                                                                                       22:32:56
ℹ Building server...                                                                                           22:32:56
✔ Server built in 5750ms                                                                                       22:33:02
✔ Generated public .output/public                                                                        nitro 22:33:02
ℹ Initializing prerenderer                                                                               nitro 22:33:02
ℹ Prerendering 9 initial routes with crawler                                                             nitro 22:33:03
  ├─ / (114ms)                                                                                           nitro 22:33:03

 ERROR  aspida is not a function                                                                               22:33:03

  at useClient (.nuxt/prerender/chunks/app/_nuxt/useApi.8a5e714f.mjs:157:22)
  at setup (.nuxt/prerender/chunks/app/_nuxt/index.6adcff2b.mjs:301:20)
  at _sfc_main$1.setup (.nuxt/prerender/chunks/app/_nuxt/index.6adcff2b.mjs:363:25)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:15:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5762:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5743:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
  at ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
  at .nuxt/prerender/chunks/app/_nuxt/index.6adcff2b.mjs:375:13
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)


 ERROR  aspida is not a function                                                                               22:33:03

  at useClient (.nuxt/prerender/chunks/app/_nuxt/useApi.8a5e714f.mjs:157:22)
  at setup (.nuxt/prerender/chunks/app/_nuxt/index.5f17c95d.mjs:32:20)
  at _sfc_main$1.setup (.nuxt/prerender/chunks/app/_nuxt/index.5f17c95d.mjs:235:25)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:15:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5762:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5743:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
  at ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
  at _sfc_ssrRender (.nuxt/prerender/chunks/app/_nuxt/index.5f17c95d.mjs:244:9)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)


 ERROR  aspida is not a function                                                                               22:33:03

  at useClient (.nuxt/prerender/chunks/app/_nuxt/useApi.8a5e714f.mjs:157:22)
  at setup (.nuxt/prerender/chunks/app/_nuxt/auth.8c7e61a5.mjs:65:20)
  at _sfc_main$1.setup (.nuxt/prerender/chunks/app/_nuxt/auth.8c7e61a5.mjs:165:25)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:15:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5762:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5743:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
  at ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
  at _sfc_ssrRender (.nuxt/prerender/chunks/app/_nuxt/auth.8c7e61a5.mjs:174:9)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)


 ERROR  aspida is not a function                                                                               22:33:03

  at useClient (.nuxt/prerender/chunks/app/_nuxt/useApi.8a5e714f.mjs:157:22)
  at setup (.nuxt/prerender/chunks/app/_nuxt/index.8670068e.mjs:33:20)
  at _sfc_main$1.setup (.nuxt/prerender/chunks/app/_nuxt/index.8670068e.mjs:188:25)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:15:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5762:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5743:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
  at ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
  at _sfc_ssrRender (.nuxt/prerender/chunks/app/_nuxt/index.8670068e.mjs:197:9)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)


 ERROR  aspida is not a function                                                                               22:33:03

  at useClient (.nuxt/prerender/chunks/app/_nuxt/useApi.8a5e714f.mjs:157:22)
  at setup (.nuxt/prerender/chunks/app/_nuxt/register.daebdcfb.mjs:33:20)
  at _sfc_main$1.setup (.nuxt/prerender/chunks/app/_nuxt/register.daebdcfb.mjs:198:25)
  at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:15:22)
  at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5762:29)
  at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.prod.js:5743:11)
  at renderComponentVNode (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:169:17)
  at ssrRenderComponent (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:621:12)
  at _sfc_ssrRender (.nuxt/prerender/chunks/app/_nuxt/register.daebdcfb.mjs:207:9)
  at renderComponentSubTree (node_modules/@vue/server-renderer/dist/server-renderer.cjs.prod.js:251:17)

  ├─ /upload (19ms)                                                                                      nitro 22:33:03
  ├─ /200.html (1ms)                                                                                     nitro 22:33:03
  ├─ /404.html (1ms)                                                                                     nitro 22:33:03
  ├─ /_payload.js (0ms)                                                                                  nitro 22:33:03
  ├─ /upload/_payload.js (1ms)                                                                           nitro 22:33:03
✔ You can now deploy .output/public to any static hosting!                                                     22:33:03
✨  Done in 14.90s.
```

**Comment by nac-39** [comment]
違うエラーが出るぞ…あれれ…
```
/workspace # yarn generate
yarn run v1.22.19
$ nuxt generate
Nuxi 3.0.0                                                                                                                                        08:00:20
Nuxt 3.0.0 with Nitro 1.0.0                                                                                                                       08:00:21

 WARN  Using experimental payload extraction for full-static output. You can opt-out by setting experimental.payloadExtraction to false.          08:00:21


 WARN  Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification                                     08:00:31


 WARN                                                                                                                                             08:00:32
(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.

ℹ Client built in 10290ms                                                                                                                         08:00:32
ℹ Building server...                                                                                                                              08:00:32
✔ Server built in 11417ms                                                                                                                         08:00:44
✔ Generated public .output/public                                                                                                           nitro 08:00:44
ℹ Initializing prerenderer                                                                                                                  nitro 08:00:44
ℹ Prerendering 9 initial routes with crawler                                                                                                nitro 08:00:46
  ├─ / (122ms)                                                                                                                              nitro 08:00:47

 ERROR  connect ECONNREFUSED 127.0.0.1:8080                                                                                                       08:00:47

  at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)

  ├─ /lecture-list (45ms)                                                                                                                   nitro 08:00:47
  ├─ /login (20ms)                                                                                                                          nitro 08:00:47
  ├─ /signup/auth (13ms)                                                                                                                    nitro 08:00:47
false                                                                                                                                             08:00:47
  ├─ /signup (25ms)                                                                                                                         nitro 08:00:47
  ├─ /signup/register (17ms)                                                                                                                nitro 08:00:47
  ├─ /upload (27ms)                                                                                                                         nitro 08:00:47
  ├─ /200.html (4ms)                                                                                                                        nitro 08:00:47
  ├─ /404.html (3ms)                                                                                                                        nitro 08:00:47
  ├─ /_payload.js (2ms)                                                                                                                     nitro 08:00:47
  ├─ /lecture-list/_payload.js (2ms)                                                                                                        nitro 08:00:47
  ├─ /login/_payload.js (2ms)                                                                                                               nitro 08:00:47
  ├─ /signup/auth/_payload.js (1ms)                                                                                                         nitro 08:00:47
  ├─ /signup/_payload.js (1ms)                                                                                                              nitro 08:00:47
  ├─ /signup/register/_payload.js (1ms)                                                                                                     nitro 08:00:47
  ├─ /upload/_payload.js (1ms)                                                                                                              nitro 08:00:47
✔ You can now deploy .output/public to any static hosting!                                                                                        08:00:47
Done in 26.38s.
```

**Comment by nac-39** [comment]
なんかこのエラーでなくなったからとりあえずクローズ
