### ISSUE TITLE
yarn installでエラーが出るようになった

### ISSUE THREAD

**Issue by nac-39** [NU-wiki-web/nu-wiki-frontend#88]
## 問題
- コンテナをビルドし直そうとしたらエラーが出るようになってしまった
  - `node-gyp`のビルドエラー
  - →alpineを使っているので、イメージにPythonが入って無くてエラーが出る
  - →今までエラーが出なかったのが逆に謎()
 ## 解決方法
- nodeのイメージをbullseyeに変更
  - `node-gyp`のインストールに必要な諸々が入るはず
- Dockerfileを記述するようにする
  - gitを入れて、コンテナの中でもhuskyが走るようにしたい
  - `yarn install`がビルド時に走るようにしたい

**Comment by nac-39** [comment]
## エラー詳細
```
% docker compose logs -f      
yarn add v1.22.19
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
warning vscode-languageclient@7.0.0: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
warning " > @aspida/axios@1.14.0" has unmet peer dependency "aspida@^1.14.0".
warning " > @aspida/fetch@1.14.0" has unmet peer dependency "aspida@^1.14.0".
warning " > @tato30/vue-pdf@1.8.1" has unmet peer dependency "vue@^3.2.33".
warning " > vuetify@3.3.22" has unmet peer dependency "vue@^3.2.0".
warning " > eslint-config-prettier@8.10.0" has unmet peer dependency "eslint@>=7.0.0".
[4/4] Building fresh packages...



error /workspace/node_modules/inotify: Command failed.
nu-wiki-frontend-node-1  | Exit code: 1
nu-wiki-frontend-node-1  | Command: node-gyp rebuild
nu-wiki-frontend-node-1  | Arguments: 
nu-wiki-frontend-node-1  | Directory: /workspace/node_modules/inotify
nu-wiki-frontend-node-1  | Output:
nu-wiki-frontend-node-1  | gyp info it worked if it ends with ok
nu-wiki-frontend-node-1  | gyp info using node-gyp@10.0.1
nu-wiki-frontend-node-1  | gyp info using node@18.19.1 | linux | x64
nu-wiki-frontend-node-1  | gyp ERR! find Python 
nu-wiki-frontend-node-1  | gyp ERR! find Python Python is not set from command line or npm configuration
nu-wiki-frontend-node-1  | gyp ERR! find Python Python is not set from environment variable PYTHON
nu-wiki-frontend-node-1  | gyp ERR! find Python checking if "python3" can be used
nu-wiki-frontend-node-1  | gyp ERR! find Python - executable path is ""
nu-wiki-frontend-node-1  | gyp ERR! find Python - "" could not be run
nu-wiki-frontend-node-1  | gyp ERR! find Python checking if "python" can be used
nu-wiki-frontend-node-1  | gyp ERR! find Python - executable path is ""
nu-wiki-frontend-node-1  | gyp ERR! find Python - "" could not be run
nu-wiki-frontend-node-1  | gyp ERR! find Python 
nu-wiki-frontend-node-1  | gyp ERR! find Python **********************************************************
nu-wiki-frontend-node-1  | gyp ERR! find Python You need to install the latest version of Python.
nu-wiki-frontend-node-1  | gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
nu-wiki-frontend-node-1  | gyp ERR! find Python you can try one of the following options:
nu-wiki-frontend-node-1  | gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
nu-wiki-frontend-node-1  | gyp ERR! find Python (accepted by both node-gyp and npm)
nu-wiki-frontend-node-1  | gyp ERR! find Python - Set the environment variable PYTHON
nu-wiki-frontend-node-1  | gyp ERR! find Python - Set the npm configuration variable python:
nu-wiki-frontend-node-1  | gyp ERR! find Python npm config set python "/path/to/pythonexecutable"
nu-wiki-frontend-node-1  | gyp ERR! find Python For more information consult the documentation at:
nu-wiki-frontend-node-1  | gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
nu-wiki-frontend-node-1  | gyp ERR! find Python **********************************************************
nu-wiki-frontend-node-1  | gyp ERR! find Python 
nu-wiki-frontend-node-1  | gyp ERR! configure error 
nu-wiki-frontend-node-1  | gyp ERR! stack Error: Could not find any Python installation to use
nu-wiki-frontend-node-1  | gyp ERR! stack at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:306:11)
nu-wiki-frontend-node-1  | gyp ERR! stack at PythonFinder.findPython (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:164:17)
nu-wiki-frontend-node-1  | gyp ERR! stack at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
nu-wiki-frontend-node-1  | gyp ERR! stack at async configure (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:23:18)
nu-wiki-frontend-node-1  | gyp ERR! stack at async run (/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js:81:18)
```
